### ISSUE TITLE
Roadmap: multiple hosts support

### ISSUE THREAD

**Issue by Nastradamus** [postgres-ai/postgres-health-check#64]
- Master
- Standbys (autodetect?)
- [x] Generate nodes.json from template (6h)https://github.com/postgres-ai/postgres-health-check/issues/89
- [x] Extend nodes.json from each run (6h)https://github.com/postgres-ai/postgres-health-check/issues/90
- [x] Refactor artifacts directory scheme (6h) https://github.com/postgres-ai/postgres-health-check/issues/91
- [x] Epoch support (6h) https://github.com/postgres-ai/postgres-health-check/issues/92

**Comment by Nastradamus** [comment]
<img width="689" alt="image" src="https://user-images.githubusercontent.com/1119739/48906496-a6186100-ee75-11e8-84c3-009ea1f8ba63.png">

**Comment by Nastradamus** [comment]
<img width="929" alt="image" src="https://user-images.githubusercontent.com/1119739/48907152-b16c8c00-ee77-11e8-9957-afb19d43abaa.png">

**Comment by Nastradamus** [comment]
We can't not use several hosts in one run: the program will be complex to much - to much variants and branches of code. We should use a single host check with ability to add an extra runs for another hosts.

**Comment by Nastradamus** [comment]
I think everything is done here.
